name: Build and Publish to npm

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install and Build 🔧
        run: |
          npm i -g pnpm
          pnpm i
          pnpm run build
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
